
[package]
description = The standard library for the
    Horse64 Root programming language.
name = root.horse64.org
version = 2025.09.22-dev
license files = /LICENSE.md
code files = src/**.r64, tests/**.r64
tools code files =
documentation files = /README.md
extra files = /AUTHORS.md,

[source repository]
latest release branch = stable
release tag format = release-*

